# Site settings
title: Thanh's Stuffs
email: dondmt@gmail.com
description: >
  This is my description
baseurl: ""
url: "http://thanhdonnguyen.github.io"

# Collections
#collections:
#  books:
#    output: false

sass:
  style: compressed
